export const SNIPPETS: Record<string, string[]> = {
  bst: [
    "public class Main {",
    "  static class Node {",
    "    int value;",
    "    Node left, right;",
    "    Node(int value) { this.value = value; }",
    "  }",
    "",
    "  static Node insert(Node root, int value) {",
    "    if (root == null) {",
    "      return new Node(value);",
    "    }",
    "    if (value < root.value) {",
    "      root.left = insert(root.left, value);",
    "    } else if (value > root.value) {",
    "      root.right = insert(root.right, value);",
    "    }",
    "    return root;",
    "  }",
    "",
    "  static Node remove(Node root, int value) {",
    "    if (root == null) {",
    "      return null;",
    "    }",
    "    if (value < root.value) {",
    "      root.left = remove(root.left, value);",
    "    } else if (value > root.value) {",
    "      root.right = remove(root.right, value);",
    "    } else {",
    "      if (root.right == null) {",
    "        return root.left;",
    "      }",
    "      if (root.left == null) {",
    "        return root.right;",
    "      }",
    "      Node min = root.right;",
    "      while (min.left != null) {",
    "        min = min.left;",
    "      }",
    "      root.value = min.value;",
    "      root.right = remove(root.right, root.value);",
    "    }",
    "    return root;",
    "  }",
    "",
    "  public static void main(String[] args) {",
    "    Node root = null;",
    "    // @@INSERT_HERE@@",
    "  }",
    "}"
  ],
  intlist: [
    "public class Main {",
    "  static class IntList {",
    "    int data;",
    "    IntList next;",
    "    IntList(int data) { this.data = data; }",
    "  }",
    "",
    "  static IntList append(IntList head, int data) {",
    "    if (head == null) {",
    "       head = new IntList(data);",
    "       return head;",
    "    }",
    "    IntList curr = head;",
    "    while (curr.next != null) {",
    "       curr = curr.next;",
    "    }",
    "    curr.next = new IntList(data);",
    "    return head;",
    "  }",
    "",
    "  static IntList remove(IntList head, int data) {",
    "    if (head == null) {",
    "      return null;",
    "    }",
    "    if (head.data == data) {",
    "       head = head.next;",
    "       return head;",
    "    }",
    "    IntList curr = head;",
    "    while (curr.next != null && curr.next.data != data) {",
    "       curr = curr.next;",
    "    }",
    "    if (curr.next != null) {",
    "       curr.next = curr.next.next;",
    "    }",
    "    return head;",
    "  }",
    "",
    "  public static void main(String[] args) {",
    "    IntList root = null;",
    "    // @@INSERT_HERE@@",
    "  }",
    "}"
  ]
}

export function getSnippetForTopic(topic: string): string[] {
  if (topic === "intlist") {
    return SNIPPETS.intlist;
  }
  return SNIPPETS.bst;
}
